on: push
jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
      - uese: actions/checkout@v2
      - uses: ./.github/actions/hello
        id: hello
        with:
          who-to-greet: "world"
      - run: |
        echo "time: ${{steps.hello.outputs.time}}"